Message décrivant les modifications

diff --git a/dockerfiles/hadoop-base/Dockerfile b/dockerfiles/hadoop-base/Dockerfile
--- a/dockerfiles/hadoop-base/Dockerfile
+++ b/dockerfiles/hadoop-base/Dockerfile
@@ -2,14 +2,13 @@
 FROM ubuntu:20.04
 
 LABEL maintainer="BigData Consultant"
-LABEL description="Hadoop Base Image with Java 8 and Hadoop 3.3.4"
+LABEL description="Hadoop Base Image with Java 8 and Hadoop 3.3.6"
 
-# Éviter les interactions lors de l'installation
 ENV DEBIAN_FRONTEND=noninteractive
 
-# Variables d'environnement
+# Variables d'environnement avec versions mises à jour
 ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
-ENV HADOOP_VERSION=3.3.4
+ENV HADOOP_VERSION=3.3.6
 ENV HADOOP_HOME=/opt/hadoop
 ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
 ENV HADOOP_LOG_DIR=$HADOOP_HOME/logs
@@ -33,7 +32,7 @@ RUN apt-get update && apt-get install -y \
     netcat \
     && rm -rf /var/lib/apt/lists/*
 
-# Configuration SSH pour Hadoop
+# Configuration SSH
 RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
     cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
     chmod 0600 ~/.ssh/authorized_keys && \
@@ -41,26 +40,31 @@ RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
     echo "  StrictHostKeyChecking no" >> ~/.ssh/config && \
     echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
 
-# Téléchargement et installation de Hadoop
-RUN wget -q https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz && \
-    tar -xzf hadoop-${HADOOP_VERSION}.tar.gz && \
-    mv hadoop-${HADOOP_VERSION} ${HADOOP_HOME} && \
-    rm hadoop-${HADOOP_VERSION}.tar.gz
+# Téléchargement et installation de Hadoop avec retry et alternatives
+RUN set -e; \
+    cd /tmp; \
+    # Essayer plusieurs miroirs pour Hadoop
+    ( wget -q --timeout=30 --tries=3 https://dlcdn.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz || \
+      wget -q --timeout=30 --tries=3 https://archive.apache.org/dist/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz || \
+      wget -q --timeout=30 --tries=3 https://www.apache.org/dyn/closer.lua/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz?action=download -O hadoop-${HADOOP_VERSION}.tar.gz \
+    ); \
+    tar -xzf hadoop-${HADOOP_VERSION}.tar.gz; \
+    mv hadoop-${HADOOP_VERSION} ${HADOOP_HOME}; \
+    rm hadoop-${HADOOP_VERSION}.tar.gz; \
+    chown -R root:root $HADOOP_HOME
 
 # Installation d'Apache Pig
 ENV PIG_VERSION=0.17.0
 ENV PIG_HOME=/opt/pig
-RUN wget -q https://archive.apache.org/dist/pig/pig-${PIG_VERSION}/pig-${PIG_VERSION}.tar.gz && \
-    tar -xzf pig-${PIG_VERSION}.tar.gz && \
-    mv pig-${PIG_VERSION} ${PIG_HOME} && \
+RUN set -e; \
+    cd /tmp; \
+    ( wget -q --timeout=30 --tries=3 https://dlcdn.apache.org/pig/pig-${PIG_VERSION}/pig-${PIG_VERSION}.tar.gz || \
+      wget -q --timeout=30 --tries=3 https://archive.apache.org/dist/pig/pig-${PIG_VERSION}/pig-${PIG_VERSION}.tar.gz \
+    ); \
+    tar -xzf pig-${PIG_VERSION}.tar.gz; \
+    mv pig-${PIG_VERSION} ${PIG_HOME}; \
     rm pig-${PIG_VERSION}.tar.gz
 ENV PATH=$PATH:$PIG_HOME/bin
-
-# Installation du MongoDB Hadoop Connector
-RUN wget -q https://repo1.maven.org/maven2/org/mongodb/mongo-hadoop/mongo-hadoop-core/2.0.2/mongo-hadoop-core-2.0.2.jar -P $HADOOP_HOME/share/hadoop/common/lib/ && \
-    wget -q https://repo1.maven.org/maven2/org/mongodb/mongodb-driver/3.12.11/mongodb-driver-3.12.11.jar -P $HADOOP_HOME/share/hadoop/common/lib/ && \
-    wget -q https://repo1.maven.org/maven2/org/mongodb/bson/3.12.11/bson-3.12.11.jar -P $HADOOP_HOME/share/hadoop/common/lib/ && \
-    wget -q https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-core/3.12.11/mongodb-driver-core-3.12.11.jar -P $HADOOP_HOME/share/hadoop/common/lib/
 
 # Création des répertoires nécessaires
 RUN mkdir -p /hadoop/dfs/name && \
@@ -71,35 +75,23 @@ RUN mkdir -p /hadoop/dfs/name && \
     mkdir -p /data
 
 # Configuration des permissions
-RUN chown -R root:root $HADOOP_HOME && \
-    chown -R root:root /hadoop && \
+RUN chown -R root:root /hadoop && \
     chmod +x $HADOOP_HOME/bin/* && \
     chmod +x $HADOOP_HOME/sbin/*
-
-# Configuration Hadoop par défaut
-RUN echo '<?xml version="1.0" encoding="UTF-8"?>' > $HADOOP_CONF_DIR/core-site.xml && \
-    echo '<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>' >> $HADOOP_CONF_DIR/core-site.xml && \
-    echo '<configuration>' >> $HADOOP_CONF_DIR/core-site.xml && \
-    echo '</configuration>' >> $HADOOP_CONF_DIR/core-site.xml
 
 # Variables d'environnement pour Hadoop
 RUN echo "export JAVA_HOME=$JAVA_HOME" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
     echo "export HADOOP_HOME=$HADOOP_HOME" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
-    echo "export HADOOP_CONF_DIR=$HADOOP_CONF_DIR" >> $HADOOP_CONF_DIR/hadoop-env.sh && \
-    echo "export HADOOP_LOG_DIR=$HADOOP_LOG_DIR" >> $HADOOP_CONF_DIR/hadoop-env.sh
+    echo "export HADOOP_CONF_DIR=$HADOOP_CONF_DIR" >> $HADOOP_CONF_DIR/hadoop-env.sh
 
-# Configuration du service SSH
+# Configuration SSH
 RUN echo 'root:bigdata123' | chpasswd && \
-    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
-    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
-
-# Exposition des ports
-EXPOSE 9000 9870 8088 9864 9868 19888 10020 8042 8188
+    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
 
 # Point d'entrée
+EXPOSE 9000 9870 8088 9864 9868 19888 10020 8042
 WORKDIR /opt/hadoop
 
-# Script de démarrage par défaut
 COPY entrypoint.sh /entrypoint.sh
 RUN chmod +x /entrypoint.sh
 
diff --git a/dockerfiles/spark/Dockerfile b/dockerfiles/spark/Dockerfile
--- a/dockerfiles/spark/Dockerfile
+++ b/dockerfiles/spark/Dockerfile
@@ -7,14 +7,14 @@ LABEL description="Apache Spark with Hadoop support"
 # Éviter les interactions lors de l'installation
 ENV DEBIAN_FRONTEND=noninteractive
 
-# Variables d'environnement
+# Variables d'environnement avec versions mises à jour
 ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
-ENV SPARK_VERSION=3.3.1
-ENV HADOOP_VERSION=3.3
+ENV SPARK_VERSION=3.4.2
+ENV HADOOP_VERSION=3
 ENV SPARK_HOME=/opt/spark
 ENV SPARK_CONF_DIR=$SPARK_HOME/conf
 ENV SPARK_LOG_DIR=$SPARK_HOME/logs
-ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.5-src.zip
+ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.7-src.zip
 ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin:$JAVA_HOME/bin
 
 # Installation des packages de base
@@ -31,29 +31,27 @@ RUN apt-get update && apt-get install -y \
     netcat \
     && rm -rf /var/lib/apt/lists/*
 
-# Installation de Python packages pour PySpark
+# Installation des packages Python
 RUN pip3 install --no-cache-dir \
     pyspark==3.3.1 \
     numpy \
     pandas \
-    matplotlib \
-    seaborn \
-    jupyter \
-    pymongo
+    matplotlib
 
-# Téléchargement et installation de Spark
-RUN wget -q https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
-    tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && \
-    mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME} && \
-    rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz
+# Téléchargement et installation de Spark avec retry et alternatives
+RUN set -e; \
+    cd /tmp; \
+    # Essayer plusieurs miroirs pour Spark
+    ( wget -q --timeout=30 --tries=3 https://dlcdn.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz || \
+      wget -q --timeout=30 --tries=3 https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz || \
+      wget -q --timeout=30 --tries=3 https://www.apache.org/dyn/closer.lua/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz?action=download -O spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
+    ); \
+    tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz; \
+    mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} ${SPARK_HOME}; \
+    rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz; \
+    chown -R root:root $SPARK_HOME
 
-# Installation du MongoDB Spark Connector
-RUN wget -q https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/3.0.2/mongo-spark-connector_2.12-3.0.2.jar -P $SPARK_HOME/jars/ && \
-    wget -q https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-sync/4.3.4/mongodb-driver-sync-4.3.4.jar -P $SPARK_HOME/jars/ && \
-    wget -q https://repo1.maven.org/maven2/org/mongodb/bson/4.3.4/bson-4.3.4.jar -P $SPARK_HOME/jars/ && \
-    wget -q https://repo1.maven.org/maven2/org/mongodb/mongodb-driver-core/4.3.4/mongodb-driver-core-4.3.4.jar -P $SPARK_HOME/jars/
-
-# Création des répertoires nécessaires
+# Création des répertoires
 RUN mkdir -p $SPARK_LOG_DIR && \
     mkdir -p $SPARK_CONF_DIR && \
     mkdir -p /scripts && \
@@ -61,39 +59,22 @@ RUN mkdir -p $SPARK_LOG_DIR && \
     mkdir -p /tmp/spark-events
 
 # Configuration des permissions
-RUN chown -R root:root $SPARK_HOME && \
-    chmod +x $SPARK_HOME/bin/* && \
+RUN chmod +x $SPARK_HOME/bin/* && \
     chmod +x $SPARK_HOME/sbin/*
 
 # Configuration Spark par défaut
 RUN echo "spark.master=spark://spark-master:7077" > $SPARK_CONF_DIR/spark-defaults.conf && \
-    echo "spark.sql.adaptive.enabled=true" >> $SPARK_CONF_DIR/spark-defaults.conf && \
-    echo "spark.sql.adaptive.coalescePartitions.enabled=true" >> $SPARK_CONF_DIR/spark-defaults.conf && \
-    echo "spark.sql.warehouse.dir=hdfs://namenode:9000/spark-warehouse" >> $SPARK_CONF_DIR/spark-defaults.conf && \
-    echo "spark.eventLog.enabled=true" >> $SPARK_CONF_DIR/spark-defaults.conf && \
-    echo "spark.eventLog.dir=hdfs://namenode:9000/spark-logs" >> $SPARK_CONF_DIR/spark-defaults.conf && \
-    echo "spark.history.fs.logDirectory=hdfs://namenode:9000/spark-logs" >> $SPARK_CONF_DIR/spark-defaults.conf
+    echo "spark.sql.adaptive.enabled=true" >> $SPARK_CONF_DIR/spark-defaults.conf
 
-# Variables d'environnement pour Spark
+# Variables d'environnement
 RUN echo "export JAVA_HOME=$JAVA_HOME" > $SPARK_CONF_DIR/spark-env.sh && \
     echo "export SPARK_HOME=$SPARK_HOME" >> $SPARK_CONF_DIR/spark-env.sh && \
-    echo "export SPARK_CONF_DIR=$SPARK_CONF_DIR" >> $SPARK_CONF_DIR/spark-env.sh && \
-    echo "export SPARK_LOG_DIR=$SPARK_LOG_DIR" >> $SPARK_CONF_DIR/spark-env.sh && \
-    echo "export PYSPARK_PYTHON=python3" >> $SPARK_CONF_DIR/spark-env.sh && \
-    echo "export PYTHONPATH=$PYTHONPATH" >> $SPARK_CONF_DIR/spark-env.sh
-
-# Configuration des workers
-RUN echo "spark-worker1" > $SPARK_CONF_DIR/workers && \
-    echo "spark-worker2" >> $SPARK_CONF_DIR/workers && \
-    echo "spark-worker3" >> $SPARK_CONF_DIR/workers
-
-# Exposition des ports
-EXPOSE 8080 7077 4040 18080 8081
+    echo "export PYSPARK_PYTHON=python3" >> $SPARK_CONF_DIR/spark-env.sh
 
 # Point d'entrée
+EXPOSE 8080 7077 4040 18080 8081
 WORKDIR /opt/spark
 
-# Script de démarrage
 COPY entrypoint.sh /entrypoint.sh
 RUN chmod +x /entrypoint.sh
 
